In [7]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import plotly.express as px
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("clean_df.csv") 

In [8]:
df = pd.read_csv("df.csv") 
dfs = df.copy()

In [9]:
dfs.head()

Unnamed: 0   Loan_ID Gender Married Dependents     Education Self_Employed  \
0           0  LP001002   Male      No          0      Graduate            No   
1           1  LP001003   Male     Yes          1      Graduate            No   
2           2  LP001005   Male     Yes          0      Graduate           Yes   
3           3  LP001006   Male     Yes          0  Not Graduate            No   
4           4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  ApplicantIncomeBin  \
0             1.0         Urban           Y                   3   
1             1.0         Rural           N                   2   
2             1.0         Urban           Y                   1   
3             1.0         Urban           Y                   0   
4             1.0         Urban           Y                   3   

   CoapplicantIncomeBin  LoanAmountBin  
0                   NaN            NaN  
1                   2.0            1.0  
2                   NaN            0.0  
3                   3.0            1.0  
4                   NaN            2.0

In [29]:
def col_drop(input_df):
    return(input_df.drop(['Loan_ID','Unnamed: 0'],axis=1,inplace=True))
def bool_tran(input_df):
    return (input_df.replace(['Y','Yes','Male','Graduate','N','No','Female', 'Not Graduate'],[True,True,True,True,False,False,False,False],inplace=True))
def married_nan(input_df):
    return dfs.dropna(subset=['Married'],inplace=True)


In [30]:
col_drop(dfs)

In [31]:
bool_tran(dfs)

In [32]:
married_nan(dfs)

In [33]:
dfs

Gender  Married Dependents  Education Self_Employed  ApplicantIncome  \
0     True    False          0       True         False             5849   
1     True     True          1       True         False             4583   
2     True     True          0       True          True             3000   
3     True     True          0      False         False             2583   
4     True    False          0       True         False             6000   
..     ...      ...        ...        ...           ...              ...   
609  False    False          0       True         False             2900   
610   True     True         3+       True         False             4106   
611   True     True          1       True         False             8072   
612   True     True          2       True         False             7583   
613  False    False          0       True          True             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0         NaN             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

    Property_Area  Loan_Status  ApplicantIncomeBin  CoapplicantIncomeBin  \
0           Urban         True                   3                   NaN   
1           Rural        False                   2                   2.0   
2           Urban         True                   1                   NaN   
3           Urban         True                   0                   3.0   
4           Urban         True                   3                   NaN   
..            ...          ...                 ...                   ...   
609         Rural         True                   1                   NaN   
610         Rural         True                   2                   NaN   
611         Urban         True                   3                   1.0   
612         Urban         True                   3                   NaN   
613     Semiurban        False                   2                   NaN   

     LoanAmountBin  
0              NaN  
1              1.0  
2              0.0  
3              1.0  
4              2.0  
..             ...  
609            0.0  
610            0.0  
611            3.0  
612            3.0  
613            2.0  

[611 rows x 15 columns]

In [36]:
dfs['Dependents'].value_counts()

0     345
1     102
2     101
3+     51
Name: Dependents, dtype: int64

In [9]:
dfs.isnull().sum()

Gender                   13
Married                   0
Dependents               12
Education                 0
Self_Employed            32
ApplicantIncome           0
CoapplicantIncome         0
LoanAmount               21
Loan_Amount_Term         14
Credit_History           50
Property_Area             0
Loan_Status               0
ApplicantIncomeBin        0
CoapplicantIncomeBin    271
LoanAmountBin            21
dtype: int64

In [4]:
dfs['Gender'] = LabelEncoder().fit_transform(dfs['Gender'])

In [5]:
dfs['Married'] = LabelEncoder().fit_transform(dfs['Married'])

In [6]:
dfs['Education'] = LabelEncoder().fit_transform(dfs['Education'])

In [7]:
dfs['Self_Employed'] = LabelEncoder().fit_transform(dfs['Self_Employed'])

In [8]:
dfs['Loan_Amount_Term'] = LabelEncoder().fit_transform(dfs['Loan_Amount_Term'])

In [9]:
dfs['Property_Area'] = LabelEncoder().fit_transform(dfs['Property_Area'])

In [10]:
dfs['Loan_Status'] = LabelEncoder().fit_transform(dfs['Loan_Status'])

In [11]:
dfs['Dependents'] = LabelEncoder().fit_transform(dfs['Dependents'])

In [13]:
dfs['CoapplicantIncomeBin'].fillna(0,inplace=True)

In [14]:
dfs.isnull().sum()

Gender                   0
Married                  0
Dependents               0
Education                0
Self_Employed            0
ApplicantIncome          0
CoapplicantIncome        0
LoanAmount              22
Loan_Amount_Term         0
Credit_History          50
Property_Area            0
Loan_Status              0
ApplicantIncomeBin       0
CoapplicantIncomeBin     0
LoanAmountBin           22
dtype: int64

In [15]:
dff = dfs.copy()

In [16]:
dff.dropna(subset=['LoanAmount'],inplace=True)

### Impute missing Credit History with KNNImputer

In [17]:
from sklearn.impute import KNNImputer

imputer = KNNImputer()
imputed_data = imputer.fit_transform(dff)  # impute all the missing data
df_temp = pd.DataFrame(imputed_data)
df_temp.columns = dff.columns

In [18]:
df_temp.isnull().sum()

Gender                  0
Married                 0
Dependents              0
Education               0
Self_Employed           0
ApplicantIncome         0
CoapplicantIncome       0
LoanAmount              0
Loan_Amount_Term        0
Credit_History          0
Property_Area           0
Loan_Status             0
ApplicantIncomeBin      0
CoapplicantIncomeBin    0
LoanAmountBin           0
dtype: int64

In [19]:
conditions = [(df_temp['Credit_History'] < .5),(df_temp['Credit_History'] >= .5)]
choices = [0,1]
df_temp['Credit_History'] = np.select(conditions,choices,default=1)

In [20]:
df_temp['Credit_History'].value_counts()

1    506
0     86
Name: Credit_History, dtype: int64

In [21]:
df_temp.to_csv('clean_df.csv',index=False)

In [10]:
df_temp.columns

NameError: name 'df_temp' is not defined

In [23]:
X = df_temp.drop(['Loan_Status'], axis=1)
y = df_temp['Loan_Status']

In [66]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### KNN

In [68]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [69]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[17 23]
 [ 7 72]]


0.7478991596638656

### Logistic Regression

In [84]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [86]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import mean_absolute_error as mae
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(mae(y_test,y_pred))
print(sqrt(mse(y_test,y_pred)))
print(accuracy_score(y_test, y_pred))

[[17 23]
 [ 1 78]]
0.20168067226890757
0.44908871313907184
0.7983193277310925


### Random Forest Classification

In [72]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'gini', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10, random_state=0)

In [73]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[19 21]
 [15 64]]


0.6974789915966386

## Decision Tree

In [74]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [75]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(sqrt(mse(y_test,y_pred)))
print(accuracy_score(y_test, y_pred))

[[22 18]
 [13 66]]
0.5103961223213518
0.7394957983193278


In [76]:
import xgboost as xgb

In [77]:
model_imb = xgb.XGBClassifier(alpha=.01,
                             learning_rate = 0.1,
                             max_depth = 10,
                             min_child_weight = 7,
                             n_estimators = 100,
                             objective = 'binary:logistic',
                             scale_pos_weight = 0.75,
                             subsample = 0.7)
                                   
model_imb.fit(X_train, y_train)

[12:33:29] WARNING: /opt/concourse/worker/volumes/live/7a2b9f41-3287-451b-6691-43e9a6c0910f/volume/xgboost-split_1619728204606/work/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


/Users/scm/opt/anaconda3/envs/lighthouselabs_env/lib/python3.6/site-packages/xgboost/sklearn.py:888: UserWarning:

The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].



XGBClassifier(alpha=0.01, base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.1, max_delta_step=0, max_depth=10,
              min_child_weight=7, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=12, num_parallel_tree=1, random_state=0,
              reg_alpha=0.00999999978, reg_lambda=1, scale_pos_weight=0.75,
              subsample=0.7, tree_method='exact', validate_parameters=1,
              verbosity=None)

In [78]:
print("Accuracy on training set: {:.2f}".format(model_imb.score(X_train, y_train) * 100))
print("Accuracy on validation set: {:.2f}".format(model_imb.score(X_test, y_test) * 100))

xgb_predict = model_imb.predict(X_test)
xgb_predict

print(confusion_matrix(y_test,xgb_predict))
print(classification_report(y_test,xgb_predict))



Accuracy on training set: 86.89
Accuracy on validation set: 76.47
[[19 21]
 [ 7 72]]


NameError: name 'classification_report' is not defined

In [79]:
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import mean_squared_error as mse
from math import sqrt


In [80]:
classifier = BaggingClassifier()
classifier.fit(X_train,y_train)

BaggingClassifier()

In [81]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(sqrt(mse(y_test,y_pred)))

[[20 20]
 [10 69]]
0.7478991596638656
0.5020964452534338


In [24]:
from sklearn.preprocessing import StandardScaler, RobustScaler, QuantileTransformer
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.decomposition import PCA
from sklearn.linear_model import Ridge


In [27]:
# This dataset is way too high-dimensional. Better do PCA:
pca = PCA(n_components=2)

# Maybe some of the original features were good, too?
selection = SelectKBest(k=3)

In [29]:
from sklearn.pipeline import Pipeline, FeatureUnion
# Build an 
#transformer from PCA and Univariate selection:
combined_features = FeatureUnion([("pca", pca), ("univ_select", selection)])

In [30]:
# Build an transformer from PCA and Univariate selection:
combined_features = FeatureUnion([("pca", pca), ("univ_select", selection)])

In [31]:
# We will initialize the classifier
svm = SVC(kernel="linear")

NameError: name 'SVC' is not defined

In [90]:
from sklearn.pipeline import Pipeline
pipe = Pipeline([
        ('scaler', StandardScaler()),
        ('reduce_dim', PCA()),
        ('classifier', logisticre)
        ])

pipe = pipe.fit(X_train, y_train)
print('Testing score: ', pipe.score(X_test, y_test))

Testing score:  0.2775179078955289


In [25]:
n_features_to_test = np.arange(1, 11)
alpha_to_test = 2.0**np.arange(-6, +6)
params = {'reduce_dim__n_components': n_features_to_test,\
              'regressor__alpha': alpha_to_test}

In [26]:
from sklearn.model_selection import GridSearchCV
gridsearch = GridSearchCV(pipe, params, verbose=1).fit(X_train, y_train)
print('Final score is: ', gridsearch.score(X_test, y_test))

NameError: name 'pipe' is not defined

In [93]:
gridsearch.best_params_

{'reduce_dim__n_components': 9, 'regressor__alpha': 4.0}

In [100]:
n_features_to_test = np.arange(1, 11)
alpha_to_test = 2.0**np.arange(-6, +6)
scalers_to_test = [StandardScaler(), RobustScaler()]

In [101]:
params = {'scaler': scalers_to_test,
        'reduce_dim__n_components': n_features_to_test,\
        'regressor__alpha': alpha_to_test}

In [102]:
params = [
        {'scaler': scalers_to_test,
         'reduce_dim': [PCA()],
         'reduce_dim__n_components': n_features_to_test,\
         'regressor__alpha': alpha_to_test},

        {'scaler': scalers_to_test,
         'reduce_dim': [SelectKBest(f_regression)],
         'reduce_dim__k': n_features_to_test,\
         'regressor__alpha': alpha_to_test}
        ]

In [103]:
gridsearch = GridSearchCV(pipe, params, verbose=1).fit(X_train, y_train)
print('Final score is: ', gridsearch.score(X_test, y_test))

Fitting 5 folds for each of 480 candidates, totalling 2400 fits
Final score is:  0.2903949378142603


In [104]:
gridsearch.best_params_

{'reduce_dim': SelectKBest(k=1, score_func=<function f_regression at 0x7fd9b48637b8>),
 'reduce_dim__k': 1,
 'regressor__alpha': 4.0,
 'scaler': RobustScaler()}

In [2]:
dfc = pd.read_csv("clean_df.csv") 

In [5]:
dfc.drop(['Loan_Status'],axis=1,inplace=True)

In [7]:
values= list(dfc.iloc[1])

In [11]:
col=list(dfc.columns)

In [10]:
values=list(dfc.iloc[1])

In [17]:
new_list = dict(map(list,zip(col,values)))

In [18]:
new_list

{'Gender': 1.0,
 'Married': 1.0,
 'Dependents': 0.0,
 'Education': 0.0,
 'Self_Employed': 1.0,
 'ApplicantIncome': 3000.0,
 'CoapplicantIncome': 0.0,
 'LoanAmount': 66.0,
 'Loan_Amount_Term': 8.0,
 'Credit_History': 1.0,
 'Property_Area': 2.0,
 'ApplicantIncomeBin': 1.0,
 'CoapplicantIncomeBin': 0.0,
 'LoanAmountBin': 0.0}

In [19]:
json_data = new_list

In [20]:
import requests
URL = "http://0.0.0.0:8888/scoring"
r = requests.post(url=URL, json = json_data)

In [21]:
print(r.json())

JSONDecodeError: Expecting value: line 1 column 1 (char 0)